/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  Installation: [
    'installation',
    {
      type: 'category',
      label: 'amcrest2mqtt',
      items: [
        'addons/amcrest2mqtt/basic-config',
      ]
    },
    {
      type: 'category',
      label: "Remote Backup",
      items: [
        'addons/remote-backup/basic-config',
        'addons/remote-backup/blueprints-automations',
        'addons/remote-backup/resources',
        'addons/remote-backup/security',
      ]
    },
    {
      type: 'category',
      label: "rsyslog",
      items: [
        'addons/rsyslog/basic-config',
      ]
    },
    {
      type: 'category',
      label: "Tasmota Device Manager",
      items: [
        'addons/tdm/basic-config',
        'addons/tdm/resources',
      ]
    },
  ]
};

module.exports = sidebars;
